# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 11:03
from __future__ import unicode_literals

import app.models
import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_about', ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Quem Somos'")),
                ('ac_vision', ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Vis\xe3o'")),
                ('ac_mission', ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Miss\xe3o'")),
                ('ac_values', ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Valores'")),
            ],
            options={
                'verbose_name_plural': 'Sobre a Empresa',
            },
        ),
        migrations.CreateModel(
            name='AgriculturalFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_date', models.DateTimeField(default=datetime.datetime.now)),
                ('ap_file', models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo')),
                ('ap_brief_desc', models.CharField(blank=True, max_length=150, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name_plural': 'Cota\xe7\xf5es Agr\xedcolas',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event_title', models.CharField(max_length=300, verbose_name='Evento')),
                ('event_local', models.CharField(max_length=300, verbose_name='Local')),
                ('event_slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('event_description', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o')),
                ('event_video', models.CharField(blank=True, help_text='Digite a URL do v\xeddeo seguindo este exemplo: <strong>http://www.youtube.com/watch?v=aAkurCTifE0</strong>', max_length=150, verbose_name='V\xeddeo do YouTube')),
                ('event_thumbnail', models.ImageField(upload_to=app.models.get_upload_path)),
                ('event_galery_title', models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_street', models.CharField(help_text='Exemplo: Rua Rio Branco', max_length=200, verbose_name='Logradouro')),
                ('config_number', models.IntegerField(verbose_name='N\xfamero')),
                ('config_neighbourhood', models.CharField(help_text='Exemplo: Vila Falc\xe3o', max_length=200, verbose_name='Bairro')),
                ('config_email', models.EmailField(help_text='<strong>Aten\xe7\xe3o! </strong>Atrav\xe9s desse email                                         voc\xea receber\xe1 os contados enviados pelo site.', max_length=254, verbose_name='Email')),
                ('config_phone', models.CharField(help_text='Formato: (18) 9900-5544', max_length=15, verbose_name='Telefone')),
                ('config_phone_alternative', models.CharField(blank=True, help_text='Formato: (18) 9900-5544', max_length=15, verbose_name='Telefone Alternativo')),
                ('config_social_facebook', models.URLField(blank=True, help_text='Formato: https://www.facebook.com/SUA_PAGINA', verbose_name='Facebook')),
                ('config_social_youtube', models.URLField(blank=True, help_text='Formato: https://www.youtube.com/user/SEU_CANAL', verbose_name='Youtube')),
                ('config_social_instagram', models.URLField(blank=True, help_text='Formato: https://www.instagram.com/SEU_PERFIL', verbose_name='Instagram')),
            ],
            options={
                'verbose_name_plural': 'Configura\xe7\xf5es Gerais',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=app.models.get_upload_path, verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descri\xe7\xe3o breve')),
                ('main_image', models.BooleanField(verbose_name='Imagem Principal')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Galeria de Imagens',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField(default=datetime.datetime.now)),
                ('job_title', models.CharField(max_length=300, verbose_name='Tit\xfalo da Vaga')),
                ('job_description', ckeditor.fields.RichTextField(help_text='Desreva aqui as especifica\xe7\xf5es da vaga e seus pr\xe9-requisitos', max_length=300, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name_plural': 'Vagas de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_date', models.DateTimeField(default=datetime.datetime.now)),
                ('magazine_title', models.CharField(max_length=300, verbose_name='Tit\xfalo da Edi\xe7\xe3o')),
                ('magazine_description', ckeditor.fields.RichTextField(blank=True, max_length=300, verbose_name='Descri\xe7\xe3o')),
                ('magazine_file', models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name_plural': 'Revistas',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(default=datetime.datetime.now)),
                ('news_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('news_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserach_date', models.DateField(default=datetime.datetime.now)),
                ('reserach_title', models.CharField(max_length=300, verbose_name='T\xedtulo')),
                ('reserach_type', models.CharField(choices=[('cotacao_agricola', 'Cota\xe7\xe3o Agr\xedcola'), ('relatorio_agricola', 'Relatorio Agricola'), ('analise_grafica', 'Analise Gr\xe1fica'), ('call_macro', 'Call Macro')], help_text='O relat\xf3rio Cota\xe7\xe3o Agr\xedcola controla a exibi\xe7\xe3o de todos os outro.                                    Portanto sempre adicione um Cota\xe7\xe3o agr\xedcola para validar a exibi\xe7\xe3o de todos.', max_length=200, verbose_name='Tipo de Relatorio')),
                ('reserach_description', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o')),
                ('research_file', models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name_plural': 'Researchs',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_description', ckeditor.fields.RichTextField(help_text='Conte\xfado da p\xe1gina de Vendas', verbose_name='Texto da P\xe1gina')),
                ('sale_email', models.EmailField(blank=True, help_text='O email do formul\xe1rio da P\xe1gina de Vendas ser\xe1 enviado para                                                                  o email registrado no menu <a href="/admin/app/generalconfig/">Configura\xe7\xf5es Gerais</a>.                                                                  Use este campo para registrar um email adicional utilizado na P\xe1gina de Vendas.', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'P\xe1gina de Vendas',
            },
        ),
    ]
