# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_about', tinymce.models.HTMLField(verbose_name="Conte\xfado do 'Quem Somos'")),
                ('ac_vision', tinymce.models.HTMLField(verbose_name="Conte\xfado do 'Vis\xe3o'")),
                ('ac_mission', tinymce.models.HTMLField(verbose_name="Conte\xfado do 'Miss\xe3o'")),
                ('ac_values', tinymce.models.HTMLField(verbose_name="Conte\xfado do 'Valores'")),
            ],
            options={
                'verbose_name_plural': 'Sobre a Empresa',
            },
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_street', models.CharField(help_text='Exemplo: Rua Rio Branco', max_length=200, verbose_name='Logradouro')),
                ('config_number', models.IntegerField(verbose_name='N\xfamero')),
                ('config_neighbourhood', models.CharField(help_text='Exemplo: Vila Falc\xe3o', max_length=200, verbose_name='Bairro')),
                ('config_email', models.EmailField(help_text='<strong>Aten\xe7\xe3o! </strong>Atrav\xe9s desse email                                         voc\xea receber\xe1 os contados enviados pelo site.', max_length=254, verbose_name='Email')),
                ('config_phone', models.CharField(help_text='Formato: (18) 9900-5544', max_length=15, verbose_name='Telefone')),
                ('config_phone_alternative', models.CharField(blank=True, help_text='Formato: (18) 9900-5544', max_length=15, verbose_name='Telefone Alternativo')),
                ('config_social_facebook', models.URLField(blank=True, help_text='Formato: https://www.facebook.com/SUA_PAGINA', verbose_name='Facebook')),
                ('config_social_youtube', models.URLField(blank=True, help_text='Formato: https://www.youtube.com/user/SEU_CANAL', verbose_name='Youtube')),
                ('config_social_instagram', models.URLField(blank=True, help_text='Formato: https://www.instagram.com/SEU_PERFIL', verbose_name='Instagram')),
            ],
            options={
                'verbose_name_plural': 'Configura\xe7\xf5es Gerais',
            },
        ),
    ]
