# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 11:08
from __future__ import unicode_literals

import app.models
import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
                ('event_title', models.CharField(max_length=300, verbose_name='Evento')),
                ('event_local', models.CharField(max_length=300, verbose_name='Local')),
                ('event_slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('event_description', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o')),
                ('event_video', models.CharField(blank=True, help_text='Digite a URL do v\xeddeo seguindo este exemplo: <strong>http://www.youtube.com/watch?v=aAkurCTifE0</strong>', max_length=150, verbose_name='V\xeddeo do YouTube')),
                ('event_thumbnail', models.ImageField(upload_to=app.models.get_upload_path)),
                ('event_galery_title', models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
