# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 01:57
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160903_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=tinymce.models.HTMLField(help_text='Desreva aqui as especifica\xe7\xf5es da vaga e seus pr\xe9-requisitos', max_length=300, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
