# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 02:07
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160903_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_date', models.DateTimeField(default=datetime.datetime.now)),
                ('magazine_title', models.CharField(max_length=300, verbose_name='Tit\xfalo da Vaga')),
                ('magazine_description', models.CharField(blank=True, max_length=300, verbose_name='Descri\xe7\xe3o')),
                ('magazine_file', models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name_plural': 'Revistas',
            },
        ),
    ]
