# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 00:42
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20160911_0040"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.Event",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Noticias",},
            bases=("app.event",),
        ),
    ]
