# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('news_name', models.CharField(max_length=200)),
                ('news_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
