# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:51
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='news',
            name='news_description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descri\xe7\xe3o'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_galery_title',
            field=models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(default='', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='news_title',
            field=models.CharField(default='', max_length=300, verbose_name='Tit\xfalo da Not\xedcia'),
            preserve_default=False,
        ),
    ]
