# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20160911_0151"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='news',
        #     name='event_ptr',
        # ),
        # migrations.AddField(
        #     model_name='news',
        #     # name='id',
        #     field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
