# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160904_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_description', tinymce.models.HTMLField(help_text='Conte\xfado da p\xe1gina de Vendas', verbose_name='Texto da P\xe1gina')),
                ('sale_email', models.EmailField(blank=True, help_text='O email do formul\xe1rio da P\xe1gina de Vendas ser\xe1 enviado para                                                                  o email registrado no menu <a href="/admin/app/generalconfig/">Configura\xe7\xf5es Gerais</a>.                                                                  Use este campo para registrar um email adicional utilizado na P\xe1gina de Vendas.', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'P\xe1gina de Vendas',
            },
        ),
        migrations.AlterField(
            model_name='research',
            name='reserach_type',
            field=models.CharField(choices=[('cotacao_agricola', 'Cota\xe7\xe3o Agr\xedcola'), ('relatorio_agricola', 'Relatorio Agricola'), ('analise_grafica', 'Analise Gr\xe1fica'), ('call_macro', 'Call Macro')], help_text='O relat\xf3rio Cota\xe7\xe3o Agr\xedcola controla a exibi\xe7\xe3o de todos os outro.                                    Portanto sempre adicione um Cota\xe7\xe3o agr\xedcola para validar a exibi\xe7\xe3o de todos.', max_length=200, verbose_name='Tipo de Relatorio'),
        ),
    ]
