# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160904_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(help_text='Desreva aqui as especifica\xe7\xf5es da vaga e seus pr\xe9-requisitos', max_length=300, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
