# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:16
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160911_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date', models.DateTimeField(default=datetime.datetime.now)),
                ('news_title', models.CharField(max_length=300, verbose_name='Tit\xfalo da Not\xedcia')),
                ('news_slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('news_description', ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o')),
                ('news_galery_title', models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
