# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cat_name', models.CharField(max_length=200, verbose_name='Nome da Categoria')),
                ('cat_slug', models.SlugField(editable=False, max_length=100)),
                ('cat_description', models.CharField(max_length=300, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name_plural': 'Categorias de Produtos',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_date', models.DateTimeField(default=datetime.datetime.now)),
                ('product_name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('product_slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('product_description', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('product_galery_title', models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductCategory')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
