# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_auto_20160911_2159"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
    ]
