# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_auto_20160912_0123"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutcompany",
            name="gallery_title",
            field=models.CharField(
                blank=True,
                help_text="Digite um nome para a Galeria de Imagens, deixe o campo embranco caso queira manter o nome como Galeria de Imagens.",
                max_length=200,
                verbose_name="T\xedtulo da Galeria de Imagens",
            ),
        ),
    ]
