# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_aboutcompany_news_galery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='news_galery_title',
        ),
    ]
