# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160918_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='config_social_twitter',
            field=models.URLField(blank=True, help_text='Formato: https://www.twitter.com/SUA_PAGINA', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_video',
            field=models.CharField(blank=True, help_text='Digite somente a parte em <strong>negrito</strong> da URL do v\xeddeoseguindo este exemplo:http://www.youtube.com/watch?v=<strong>aAkurCTifE0</strong>', max_length=150, verbose_name='V\xeddeo do YouTube'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='config_email',
            field=models.EmailField(help_text='<strong>Aten\xe7\xe3o! </strong>Atrav\xe9sdesse email voc\xea receber\xe1 os contadosenviados pelo site.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_galery_title',
            field=models.CharField(blank=True, help_text='Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queiramanter o nome como Galeria de Imagens.', max_length=200, verbose_name='T\xedtulo da Galeria de Imagens'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_short_description',
            field=models.TextField(help_text='Essa descri\xe7\xe3o ir\xe1 aparecer na homepage.', max_length=200, verbose_name='Descri\xe7\xe3o Curta'),
        ),
        migrations.AlterField(
            model_name='research',
            name='reserach_type',
            field=models.CharField(choices=[('cotacao_agricola', 'Cota\xe7\xe3o Agr\xedcola'), ('relatorio_agricola', 'Relatorio Agricola'), ('analise_grafica', 'Analise Gr\xe1fica'), ('call_macro', 'Call Macro')], help_text='O relat\xf3rio Cota\xe7\xe3o Agr\xedcola controla a exibi\xe7\xe3o de todos os outro.Portanto sempre adicione um Cota\xe7\xe3o agr\xedcola para validar a exibi\xe7\xe3o de todos.', max_length=200, verbose_name='Tipo de Relatorio'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_email',
            field=models.EmailField(blank=True, help_text='O email do formul\xe1rio da P\xe1gina de Vendas ser\xe1 enviado parao email registrado no menu <a href="/admin/app/generalconfig/">Configura\xe7\xf5es Gerais</a>.Use este campo para registrar um email adicional utilizado na P\xe1gina de Vendas.', max_length=254, verbose_name='Email'),
        ),
    ]
