# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:39
from __future__ import unicode_literals

import datetime

import app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_auto_20160918_1652"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalResponsability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environ_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="Data"
                    ),
                ),
                (
                    "environ_title",
                    models.CharField(max_length=300, verbose_name="T\xedtulo"),
                ),
                (
                    "environ_local",
                    models.CharField(max_length=300, verbose_name="Local"),
                ),
                (
                    "environ_description",
                    ckeditor.fields.RichTextField(verbose_name="Descri\xe7\xe3o"),
                ),
                (
                    "environ_video",
                    models.CharField(
                        blank=True,
                        help_text="Digite somente a parte em <strong>negrito</strong> da URL do v\xeddeoseguindo este exemplo:http://www.youtube.com/watch?v=<strong>aAkurCTifE0</strong>",
                        max_length=150,
                        verbose_name="V\xeddeo do YouTube",
                    ),
                ),
                (
                    "environ_thumbnail",
                    models.ImageField(
                        upload_to=app.models.get_upload_path, verbose_name="Thumbnail"
                    ),
                ),
                (
                    "environ_galery_title",
                    models.CharField(
                        blank=True,
                        help_text="Digite um nome para a Galeria de Imagens, deixe o campo em branco caso queira manter o nome como Galeria de Imagens.",
                        max_length=200,
                        verbose_name="T\xedtulo da Galeria de Imagens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilidade Ambiental",
                "verbose_name_plural": "Responsabilidade Ambiental",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Responsabilidade Social",
                "verbose_name_plural": "Responsabilidade Social",
            },
        ),
        migrations.AddField(
            model_name="news",
            name="news_video",
            field=models.CharField(
                blank=True,
                help_text="Digite somente a parte em <strong>negrito</strong> da URL do v\xeddeoseguindo este exemplo:http://www.youtube.com/watch?v=<strong>aAkurCTifE0</strong>",
                max_length=150,
                verbose_name="V\xeddeo do YouTube",
            ),
        ),
        migrations.AlterField(
            model_name="agriculturalfiles",
            name="ap_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Data"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_thumbnail",
            field=models.ImageField(
                upload_to=app.models.get_upload_path, verbose_name="Thumbnail"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_title",
            field=models.CharField(max_length=300, verbose_name="T\xedtulo"),
        ),
        migrations.AlterField(
            model_name="magazine", name="magazine_date", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="news", name="news_date", field=models.DateTimeField(),
        ),
    ]
