# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20161112_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='ac_language',
            field=models.CharField(choices=[('pt-br', 'Portugues'), ('en-us', 'English')], default='pt-br', help_text='Indioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Indioma'),
        ),
    ]
