# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_auto_20161120_1828"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[(b"pt", b"Portuguese"), (b"en", b"English")],
                default="pt",
                help_text="Idioma em que a p\xe1gina ser\xe1 exibida",
                max_length=5,
                verbose_name="Idioma",
            ),
        ),
    ]
