# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_aboutcompany_ac_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalresponsability',
            name='environ_language',
            field=models.CharField(choices=[('pt-br', 'Portugues'), ('en-us', 'English')], default='pt-br', help_text='Indioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Indioma'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_language',
            field=models.CharField(choices=[('pt-br', 'Portugues'), ('en-us', 'English')], default='pt-br', help_text='Indioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Indioma'),
        ),
        migrations.AddField(
            model_name='partners',
            name='partner_language',
            field=models.CharField(choices=[('pt-br', 'Portugues'), ('en-us', 'English')], default='pt-br', help_text='Indioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Indioma'),
        ),
    ]
