# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20161113_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Portugues'), ('en', 'English')], default='pt', help_text='Idioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Idioma')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='ac_language',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='id',
        ),
        migrations.RemoveField(
            model_name='environmentalresponsability',
            name='environ_language',
        ),
        migrations.RemoveField(
            model_name='environmentalresponsability',
            name='id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_language',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='id',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='partner_language',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='environmentalresponsability',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='extendme_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.extendMe'),
            preserve_default=False,
        ),
    ]
