# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_news_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('suinos', 'Suinos'), ('bovinos', 'Bovinos'), ('cafe', 'Caf\xe9')], default='suinos', help_text='Categoria do produto', max_length=20, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
