# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_products_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AboutCompany'),
        ),
        migrations.AddField(
            model_name='environmentalresponsability',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EnvironmentalResponsability'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
        migrations.AddField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.News'),
        ),
        migrations.AddField(
            model_name='partners',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Partners'),
        ),
        migrations.AddField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
        migrations.AddField(
            model_name='sale',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sale'),
        ),
    ]
