# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20161119_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalconfig',
            name='config_social_linkedin',
        ),
    ]
