# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20161203_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descri\xe7\xe3o breve'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AboutCompany', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='environmentalresponsability',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EnvironmentalResponsability', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Event', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.News', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Partners', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Products', verbose_name='P\xe1gina Original'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sale', verbose_name='P\xe1gina Original'),
        ),
    ]
