# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_generalconfig_config_social_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfig',
            name='config_social_linkedin',
            field=models.URLField(blank=True, help_text='Formato: https://www.linkedin.com/SEU_PERFIL', verbose_name='Linkedin'),
        ),
    ]
