# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-01-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20191230_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_location',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_city',
            field=models.CharField(default='', help_text='Brasil\xe2ndia', max_length=300, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_state',
            field=models.CharField(default='', help_text='MS', max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=22, null=True),
        ),
    ]
