# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200124_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_google_maps_link',
            field=models.URLField(blank=True, default='', help_text='https://www.google.com/maps?&z=15&mrt=yp&t=k&q=-17.091389,-55.739722', verbose_name='Link Google Maps'),
        ),
    ]
