# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-03-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_farm_farm_google_maps_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.DateField(unique=True)),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Descri\xe7\xe3o"),
                ),
            ],
            options={
                "verbose_name": "Linha do Tempo",
                "verbose_name_plural": "Linha do Tempo",
            },
        ),
        migrations.AlterModelOptions(
            name="products",
            options={
                "verbose_name": "P\xe1gina de Venda",
                "verbose_name_plural": "P\xe1gina de Vendas",
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "verbose_name": "P\xe1gina de Compra",
                "verbose_name_plural": "P\xe1gina de Compras",
            },
        ),
    ]
