# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-03-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200301_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='language',
            field=models.CharField(choices=[(b'pt', b'Portuguese'), (b'en', b'English')], default='pt', help_text='Idioma em que a p\xe1gina ser\xe1 exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='P\xe1gina da qual esta \xe9 uma tradu\xe7\xe3o. N\xe3o \xe9 necess\xe1rio para p\xe1ginas em Portugu\xeas', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TimeLine', verbose_name='P\xe1gina Original'),
        ),
    ]
