# Generated by Django 3.2.24 on 2025-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendar_backup', models.BooleanField(default=False, verbose_name='Agendar backup automático?')),
                ('horario', models.TimeField(default='02:00', verbose_name='Horário do backup (HH:MM)')),
            ],
        ),
    ]
