# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateTimeField(default=datetime.datetime.now)),
                ('job_title', models.CharField(max_length=300, verbose_name='Tit\xfalo da Vaga')),
                ('job_description', models.CharField(help_text='Desreva aqui as especifica\xe7\xf5es da vaga e seus pr\xe9-requisitos', max_length=300, verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name_plural': 'Vagas de Trabalho',
            },
        ),
        migrations.AlterField(
            model_name='imagem',
            name='main_image',
            field=models.BooleanField(verbose_name='Imagem Principal'),
        ),
    ]
