# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='magazine_description',
            field=tinymce.models.HTMLField(blank=True, max_length=300, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_title',
            field=models.CharField(max_length=300, verbose_name='Tit\xfalo da Edi\xe7\xe3o'),
        ),
    ]
