# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 14:44
from __future__ import unicode_literals

import app.models
import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160903_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserach_date', models.DateField(default=datetime.datetime.now)),
                ('reserach_title', models.CharField(max_length=300, verbose_name='T\xedtulo')),
                ('reserach_type', models.CharField(choices=[('cotacao_agricola', 'Cota\xe7\xe3o Agr\xedcola'), ('relatorio_agricola', 'Relatorio Agricola'), ('analise_grafica', 'Analise Gr\xe1fica'), ('call_macro', 'Call Macro')], help_text='O relat\xf3rio Cota\xe7\xe3o Agr\xedcola controla a exibi\xe7\xe3o de todos os outro. Portanto sempre adicione um Cota\xe7\xe3o agr\xedcola para validar a exibi\xe7\xe3o de todos.', max_length=200, verbose_name='Tipo de Relatorio')),
                ('reserach_description', tinymce.models.HTMLField(verbose_name='Descri\xe7\xe3o')),
                ('research_file', models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name_plural': 'Researchs',
            },
        ),
    ]
