# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='date',
            new_name='news_date',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='news_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='news_name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
