# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 14:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160905_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='ac_about',
            field=ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Quem Somos'"),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='ac_mission',
            field=ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Miss\xe3o'"),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='ac_values',
            field=ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Valores'"),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='ac_vision',
            field=ckeditor.fields.RichTextField(verbose_name="Conte\xfado do 'Vis\xe3o'"),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='magazine_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='research',
            name='reserach_description',
            field=ckeditor.fields.RichTextField(verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_description',
            field=ckeditor.fields.RichTextField(help_text='Conte\xfado da p\xe1gina de Vendas', verbose_name='Texto da P\xe1gina'),
        ),
    ]
