name: Deploy AH Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python manage.py test
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production server..."
        # Aqui você pode adicionar comandos para deploy no seu servidor
        # Por exemplo, usando SSH para conectar ao servidor e executar o deploy.sh
        
    - name: Notify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deployment completed successfully!"
        # Aqui você pode adicionar notificações (email, Slack, etc.)
