# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_event"),
    ]

    operations = [
        migrations.AlterModelOptions(name="agriculturalfiles", options={},),
        migrations.RemoveField(model_name="agriculturalfiles", name="ap_brief_desc",),
        migrations.RemoveField(model_name="agriculturalfiles", name="ap_date",),
        migrations.RemoveField(model_name="agriculturalfiles", name="ap_file",),
    ]
