# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 00:28
from __future__ import unicode_literals

import datetime

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20160910_0021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agriculturalfiles",
            options={"verbose_name_plural": "Cota\xe7\xf5es Agr\xedcolas"},
        ),
        migrations.AddField(
            model_name="agriculturalfiles",
            name="ap_brief_desc",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Descri\xe7\xe3o"
            ),
        ),
        migrations.AddField(
            model_name="agriculturalfiles",
            name="ap_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="agriculturalfiles",
            name="ap_file",
            field=models.FileField(
                null=True,
                blank=True,
                upload_to=app.models.get_upload_path,
                verbose_name="Arquivo",
            ),
        ),
    ]
