# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_auto_20160911_0152"),
    ]

    operations = [
        migrations.RemoveField(model_name="news", name="news_title",),
        migrations.DeleteModel(name="News",),
    ]
