# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:47
from __future__ import unicode_literals

import datetime

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "partner_title",
                    models.CharField(max_length=300, verbose_name="Nome da Parceria"),
                ),
                (
                    "partner_slug",
                    models.SlugField(editable=False, max_length=100, unique=True),
                ),
                (
                    "partner_description",
                    ckeditor.fields.RichTextField(verbose_name="Descri\xe7\xe3o"),
                ),
            ],
            options={"verbose_name_plural": "Parcerias",},
        ),
    ]
