# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_remove_aboutcompany_news_galery_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_description",
            field=ckeditor.fields.RichTextField(verbose_name="Descri\xe7\xe3o"),
        ),
    ]
