# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_auto_20160920_1039"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environmentalresponsability", name="environ_local",
        ),
    ]
