# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_generalconfig_config_social_linkedin"),
    ]

    operations = [
        migrations.RemoveField(model_name="research", name="reserach_description",),
        migrations.AlterField(
            model_name="research",
            name="reserach_type",
            field=models.CharField(
                choices=[
                    ("cotacao_agricola", "Cota\xe7\xe3o Agr\xedcola"),
                    ("relatorio_agricola", "Relatorio Agricola"),
                    ("analise_grafica", "Analise Gr\xe1fica"),
                    ("call_macro", "Call Macro"),
                ],
                max_length=200,
                verbose_name="Tipo de Relatorio",
            ),
        ),
    ]
