# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 15:30
from __future__ import unicode_literals

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("app", "0028_generalconfig_config_email_cv"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attach",
                    models.FileField(
                        upload_to=app.models.get_upload_path, verbose_name="Anexo"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Arquivos Anexos",},
        ),
        migrations.AddField(
            model_name="environmentalresponsability",
            name="attach_galery_title",
            field=models.CharField(
                blank=True,
                help_text="Digite um nome para a Galeria de Anexos, deixe o campo em branco caso queira manter o nome como Galeria de Anexos.",
                max_length=200,
                verbose_name="T\xedtulo da Galeria de Anexos",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="event_attach_galery_title",
            field=models.CharField(
                blank=True,
                help_text="Digite um nome para a Galeria de Anexos, deixe o campo em branco caso queira manter o nome como Galeria de Anexos.",
                max_length=200,
                verbose_name="T\xedtulo da Galeria de Anexos",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="attach_galery_title",
            field=models.CharField(
                blank=True,
                help_text="Digite um nome para a Galeria de Anexos, deixe o campo em branco caso queira manter o nome como Galeria de Anexos.",
                max_length=200,
                verbose_name="T\xedtulo da Galeria de Anexos",
            ),
        ),
    ]
