# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 00:34
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_auto_20161213_0221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="news_slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="news_title",
            field=models.CharField(
                max_length=255, verbose_name="Tit\xfalo da Not\xedcia"
            ),
        ),
    ]
