# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-12-30 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_farm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farm", old_name="farm_localizacao", new_name="farm_location",
        ),
    ]
