# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-03-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_auto_20200301_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeline", name="year", field=models.DateField(),
        ),
    ]
