# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-03-01 22:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200301_2126'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='timeline',
        #     name='year',
        #     field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1910)], verbose_name='Ano'),
        # ),
    ]
