# Generated by Django 5.2.2 on 2025-06-09 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20200301_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aboutcompany', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='agriculturalfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='environmentalresponsability',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='environmentalresponsability',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='environmentalresponsability',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.environmentalresponsability', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.news', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partners', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.products', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='research',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sale', verbose_name='Página Original'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', help_text='Idioma em que a página será exibida', max_length=5, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Página da qual esta é uma tradução. Não é necessário para páginas em Português', limit_choices_to={'language': 'pt'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.timeline', verbose_name='Página Original'),
        ),
    ]
