# Generated by Django 5.2.2 on 2025-06-11 01:41

import django.core.validators
from django.db import migrations, models

def convert_year_to_integer(apps, schema_editor):
    Timeline = apps.get_model('app', 'Timeline')
    for timeline in Timeline.objects.all():
        try:
            # Se for objeto de data
            if hasattr(timeline.year, 'year'):
                year = timeline.year.year
            # Se for string numérica
            elif isinstance(timeline.year, str) and timeline.year.isdigit():
                year = int(timeline.year)
            # Se for string tipo '2020-01-01'
            elif isinstance(timeline.year, str):
                year = int(timeline.year[:4])
            # Se for inteiro
            elif isinstance(timeline.year, int):
                year = timeline.year
            else:
                year = 2020  # valor padrão
            # Atualiza diretamente no banco, sem chamar save()
            Timeline.objects.filter(pk=timeline.pk).update(year_temp=year)
        except Exception as e:
            Timeline.objects.filter(pk=timeline.pk).update(year_temp=2020)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_aboutcompany_id_alter_aboutcompany_language_and_more'),
    ]

    operations = [
        # Adiciona campo temporário
        migrations.AddField(
            model_name='timeline',
            name='year_temp',
            field=models.IntegerField(
                default=2020,
                validators=[
                    django.core.validators.MaxValueValidator(2050),
                    django.core.validators.MinValueValidator(1910)
                ],
                verbose_name='Ano Temporário'
            ),
        ),
        # Converte os dados
        migrations.RunPython(convert_year_to_integer),
        # Remove o campo antigo
        migrations.RemoveField(
            model_name='timeline',
            name='year',
        ),
        # Renomeia o campo temporário
        migrations.RenameField(
            model_name='timeline',
            old_name='year_temp',
            new_name='year',
        ),
    ]
