# Generated by Django 5.2.2 on 2025-06-18 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_timeline_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1910)], verbose_name='Ano'),
        ),
    ]
