# Generated by Django 5.2.2 on 2025-06-25 00:32

from django.db import migrations


def delete_agricultural_files_without_file(apps, schema_editor):
    """Remove registros que não têm arquivo para permitir a migração"""
    AgriculturalFiles = apps.get_model('app', 'AgriculturalFiles')
    # Remove registros que não têm arquivo
    AgriculturalFiles.objects.filter(ap_file__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_timeline_year'),
    ]

    operations = [
        migrations.RunPython(delete_agricultural_files_without_file, reverse_code=migrations.RunPython.noop),
    ]
