# Generated by Django 5.2.2 on 2025-06-25 00:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_fix_agricultural_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalfiles',
            name='ap_file',
            field=models.FileField(upload_to=app.models.get_upload_path, verbose_name='Arquivo'),
        ),
    ]
