# Generated by Django 5.2.3 on 2025-07-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_equipecompras'),
        ('app', '0049_alter_agriculturalfiles_ap_file'),
    ]

    operations = [
    ]
