# Generated by Django 5.2.3 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_merge_20250703_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipecompras',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
