# Generated by Django 3.2.24 on 2025-07-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0051_alter_equipecompras_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('template_path', models.CharField(max_length=512, verbose_name='Caminho do Template')),
                ('content', models.TextField(verbose_name='Conteúdo do Template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup de Template',
                'verbose_name_plural': 'Backups de Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
